apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  helm.repositories: |
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com